[colors.primary]
background = "#000000"
foreground = "#5f8787"


[font]
size = 12

[font.normal]
family = "monospace"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 0
y = 0
