#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12
bspc config normal_border_color \#101010
bspc config focused_border_color \#5F81A5

bspc config focus_follows_pointer true

bspc config pointer_modifier mod1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart 
sxhkd &
nitrogen --restore &
dunst &
polybar &
