#!/bin/sh

export NSXIV_FIT_WIN_FIFO="/tmp/nsxiv_fit_win_fifo"

fit_to_win() {
  while read w h < "$NSXIV_FIT_WIN_FIFO" >/dev/null 2>&1; do
    xdo resize -h "$h" -w "$w" "$(xdo id -n nsxiv)"
  done
}

mkfifo "$NSXIV_FIT_WIN_FIFO"
trap 'rm -f "$NSXIV_FIT_WIN_FIFO"' EXIT

nsxiv "$@" & nsxiv_pid="$!"
fit_to_win & fit_to_win_pid="$!"

wait "$nsxiv_pid"; kill "$fit_to_win_pid"
