#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#name of workspaces
bspc monitor DP-4 -d I II III IV V VI VII VIII IX
bspc monitor DP-3 -d X
#borders around windows
bspc config border_width         5
bspc config window_gap          12
bspc config normal_border_color \#5F81A5
bspc config focused_border_color \#bd93f9
bspc config active_border_color \#5F81A5

#focus window with mouse cursor
bspc config focus_follows_pointer true

#use mouse settings with alt instead of super
bspc config pointer_modifier mod1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#start terminal in floating mode
bspc rule --add Alacritty state=floating rectangle=1000x500+500+500 center true

#steam starts in floating mode
bspc rule --add Steam state=floating

#spotify starts in floating mode
bspc rule --add Spotify state=floating

#nemo starts in floating mode
bspc rule --add Nemo state=floating

#remove beeping in tty
xset -b

#remove mouse when using keyboard
unclutter --jitter 30 --ignore-scrolling --start-hidden --fork --timeout 2

#Monitors
xrandr --output DP-4 --primary --mode 2560x1440 --rotate normal --rate 144 --output DP-3 --mode 1920x1080 --rotate normal --rate 60 --right-of DP-4 

#cursor options
xsetroot -cursor_name left_ptr
xset r rate 200 50
xset s off
xset -dpms

#autostart 
sxhkd &
nitrogen --restore &
dunst &
polybar &
picom &
