#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#name of workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

#borders around windows
bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color \#101010
bspc config focused_border_color \#5F81A5

#focus window with mouse cursor
bspc config focus_follows_pointer true

#use mouse settings with alt instead of super
bspc config pointer_modifier mod1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#start terminal in floating mode
bspc rule --add kitty state=floating rectangle=1000x500+500+500 center true

#remove beeping in tty
xset -b

#remove mouse when using keyboard
unclutter --jitter 30 --ignore-scrolling --start-hidden --fork --timeout 2

#autostart 
sxhkd &
nitrogen --restore &
dunst &
polybar &
picom &
